#Jesus Antonio Baez Ortega 23310372 6E
#LAB#3 Formatting the output

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("---------------------------------")
#menos lineas
print("    *\n" "   * *\n" "  *   *\n"" *     *\n" "***   ***\n"  + ("  *   *\n"*2) +"  *****")
print("---------------------------------")
#mas grande
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")
print("---------------------------------")
#uno al lado del otro
print(("    *       "*2) + "\n"  + ("   * *      ")*2 +  "\n" + ("  *   *     ")*2 + "\n" + (" *     *    ")*2 +  "\n" + ("***   ***   ")*2  + "\n" + ("  *   *     "*2) + "\n"  + ("  *   *     "*2) + "\n" + ("  *****     "*2))